version: 2.1

jobs:
  build-and-test:
    working_directory: ~/blog
    docker:
      - image: circleci/golang:1.15.8
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run tests
          command: |
            mkdir -p /tmp/test-reports
            gotestsum --junitfile /tmp/test-reports/unit-tests.xml
      - store_test_results:
          path: /tmp/test-reports

  build-and-deploy:
    working_directory: ~/blog
    docker:
      - image: circleci/golang:1.15.8
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - add_ssh_keys:
          fingerprints:
            - "42:99:78:ba:bc:ac:56:bb:33:d8:04:7d:58:a0:30:98"
      - run: echo $REMOTE_HOSTKEY >> ~/.ssh/known_hosts
      - run:
          command:
            mkdir -p /tmp/blog
            go build
            echo '==============部署开始=============='
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
            rsync -avce ~/blog/tmp/blog $USER@$IP_ADDRESS:/data/cpg-service/
            else
            echo "Not master branch, dry run only"
            fi
      - run: echo '==============部署完毕=============='

workflows:
  default:
    jobs:
      - build-and-test
      - build-and-deploy:
          filters:
            branches:
              only: master
