version: 2.1

jobs:
  build-and-test:
    working_directory: ~/test
    docker:
      - image: circleci/golang:1.15.8
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run tests
          command: |
            mkdir -p /tmp/test-reports
            gotestsum --junitfile /tmp/test-reports/unit-tests.xml
      - store_test_results:
          path: /tmp/test-reports

  build-and-deploy:
    working_directory: ~/cpg-blog
    parameters:
      hasMain:
        type: string
    docker:
      - image: circleci/golang:1.15.8
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run: sudo apt-get install rsync
      - add_ssh_keys:
          fingerprints:
            - "3c:9f:39:38:1e:9f:4c:be:6b:08:6d:e2:58:12:d6:da"
      - run: echo $HOSTKEY >> ~/.ssh/known_hosts
      - run: echo '==============部署开始=================='
      - deploy:
          name: deploy
          command: |
            if [ ${hasMain} != "" ];then
            ssh $ROOT@$IP_ADDRESS "killall main"
            fi

            if [ "${CIRCLE_BRANCH}" = "master" ]; then
            rsync -avce ssh ~/cpg-blog/ $ROOT@$IP_ADDRESS:/data/cpg-blog
            ssh $ROOT@$IP_ADDRESS "cd /data/cpg-blog/cmd/cpg/; go build main.go"
            ssh $ROOT@$IP_ADDRESS "cd /data/cpg-blog/cmd/cpg/ && nohup ./main &"
            ssh $ROOT@$IP_ADDRESS "exit"
            else
            echo "Not master branch, dry run only"
            fi
      - run: echo '==============部署完毕==== ==============='

workflows:
  version: 2
  default:
     jobs:
      - build-and-test
      - build-and-deploy:
         hasMain: ssh $ROOT@$IP_ADDRESS "ps -A | grep main"
         requires:
          - build-and-test
         filters:
            branches:
              only: master
